import { createSlice } from "@reduxjs/toolkit";

const menuDataSlice = createSlice({
  name: "menuData",
  initialState: {
    menuCategories: ["Family Dinners", "Sepcial Combo", "Fried Rice"],
    selectionItems: [
      {
        category: "Family Dinners",
        list: [
          "Appetizers",
          "Soups",
          "Sweet & Sour",
          "Chickens",
          "Chow Mein",
          "Fried Rice",
          "Lo Mein",
          "Vegetable Almond",
          "Popular Suggestions",
          "Chef Suggestions",
          "Szechaun",
          "Seafood",
          "Honey & Curry",
          "Egg Fu Young",
          "Canadian Dishes",
          "Family Dinners",
          "Extra Sauce",
          "Drinks",
          "No Add",
        ],
      },
      {
        category: "combos",
        list: [
          "Special Combo",
          "Appetizers",
          "Soups",
          "Sweet & Sour",
          "Chickens",
          "Chow Mein",
          "Fried Rice",
          "Lo Mein",
          "Vegetable Almond",
          "Popular Suggestions",
          "Chef Suggestions",
          "Szechaun",
          "Seafood",
          "Honey & Curry",
          "Egg Fu Young",
          "Canadian Dishes",
          "Family Dinners",
          "Extra Sauce",
          "Drinks",
          "No Add",
        ],
      },
    ],
    menuItems: [
      {
        name: "Dinner for 5",
        price: 65.95,
        category: ["Family Dinners"],
        quantity: 1,
        modifiers: [],
        components: ["Terriyaki Beef"],
        modifiable: true,
        swappable: true,
        selectionCategory: "combos",
      },
      {
        name: "Noodles with the Sauce",
        price: 65.95,
        category: ["Family Dinners"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "None Yea",
        price: 65.95,
        category: ["Family Dinners"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "combo",
        nickName: [],
        price: 17.95,
        category: ["Special Combo"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      // Appetizers
      {
        name: "Egg Roll",
        nickName: ["er"],
        price: 1.5,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Spring Roll",
        nickName: ["sr"],
        price: 1.75,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken Wings",
        nickName: ["ch wings"],
        price: 12.95,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Almond Soo Guy",
        nickName: ["almd so guy"],
        price: 12.95,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Deep Fried Wontons",
        nickName: ["dfwtn"],
        price: 6.95,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Breaded Shrimp",
        nickName: ["shrimp"],
        price: 12.95,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Breaded Scallops",
        nickName: [],
        price: 16.95,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken Teriyaki",
        nickName: [""],
        price: 15.95,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Teriyaki",
        nickName: [""],
        price: 15.95,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "B.B.Q Pork Slices",
        nickName: ["bbq slice"],
        price: 14.95,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "B.B.Q Pork Ribs",
        nickName: ["bbq ribs"],
        price: 15.95,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: true,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Bo Bo Tray For Two",
        nickName: ["bo bo 2"],
        price: 22.95,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Bo Bo Tray for Four",
        nickName: ["bo bo 4"],
        price: 43.95,
        category: ["Appetizers"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      // Soups
      {
        name: "Wonton Soup (L)",
        nickName: ["wtn", "wt", "soup", "wtn soup"],
        price: 4.95,
        category: ["Soups"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Wonton Soup (S)",
        nickName: ["wtn", "wt", "soup", "wtn soup"],
        price: 4.5,
        category: ["Soups"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Hot and Sour Soup",
        nickName: ["soup"],
        price: 4.95,
        category: ["Soups"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken Noodle Soup",
        nickName: ["soup", "ch noodle soup", "ch soup"],
        price: 4.95,
        category: ["Soups"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Noodle Soup",
        nickName: ["soup", "beef noodle soup", "beef soup"],
        price: 4.95,
        category: ["Soups"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Pork Noodle Soup",
        nickName: ["soup", "pork noodle soup", "pork soup"],
        price: 4.95,
        category: ["Soups"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Fine Noodle Soup",
        nickName: ["soup", "fine noodle"],
        price: 4.95,
        category: ["Soups"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Egg Flower Soup",
        nickName: ["soup"],
        price: 4.95,
        category: ["Soups"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Consomme Soup",
        nickName: ["soup"],
        price: 4.0,
        category: ["Soups"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Miso Soup",
        nickName: ["soup"],
        price: 4.95,
        category: ["Soups"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      //Sweet and Sour
      {
        name: "Sweet and Sour Chicken Balls",
        nickName: ["sts", "ss", "sts ch balls", "ch balls"],
        price: 12.95,
        category: ["Sweet & Sour"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Pineapple Chicken Balls",
        nickName: ["sts", "ss", "sts ch balls", "ch balls"],
        price: 12.95,
        category: ["Sweet & Sour"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Sweet and Sour Pork",
        nickName: ["sts", "ss", "sts pork"],
        price: 9.95,
        category: ["Sweet & Sour"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Sweet and Sour Spare Ribs",
        nickName: ["sts", "ss", "sts ribs"],
        price: 9.95,
        category: ["Sweet & Sour"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Sweet and Sour Breaded Shrimp",
        nickName: ["sts", "ss", "shrimp", "breaded shrimp"],
        price: 12.95,
        category: ["Sweet & Sour"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Deep Fried Wontons",
        nickName: ["dfwtn"],
        price: 6.95,
        category: ["Sweet & Sour"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Sweet and Sour Breaded Scallops",
        nickName: ["sts", "ss", "scallops"],
        price: 16.95,
        category: ["Sweet & Sour"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Sweet and Sour Beef",
        nickName: ["sts", "ss", "sts beef"],
        price: 11.95,
        category: ["Sweet & Sour"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      //Chow Mein & Chop Suey
      {
        name: "Chicken Chop Suey",
        nickName: ["ch cs", "ch cm", "cm"],
        price: 9.95,
        category: ["Chow Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Chop Suey",
        nickName: ["beef cs", "cm", "beef cm"],
        price: 9.95,
        category: ["Chow Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Pork Chop Suey",
        nickName: ["cs", "cm", "pork cs", "pork cm"],
        price: 9.95,
        category: ["Chow Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Shrimp Chop Suey",
        nickName: ["cs", "cm", "shrimp cs", "shrimp cm"],
        price: 12.95,
        category: ["Chow Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Harmony Chop Suey",
        nickName: ["cs", "cm", "harm cs", "harm cm"],
        price: 12.95,
        category: ["Chow Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },

      {
        name: "Chicken Chow Mein",
        nickName: ["ch cs", "ch cm", "cm"],
        price: 10.95,
        category: ["Chow Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Chow Mein",
        nickName: ["beef cs", "cm", "beef cm"],
        price: 10.95,
        category: ["Chow Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Pork Chow Mein",
        nickName: ["cs", "cm", "pork cs", "pork cm"],
        price: 10.95,
        category: ["Chow Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Shrimp Chow Mein",
        nickName: ["cs", "cm", "shrimp cs", "shrimp cm"],
        price: 13.95,
        category: ["Chow Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Harmony Chow Mein",
        nickName: ["cs", "cm", "harm cs", "harm cm"],
        price: 13.95,
        category: ["Chow Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Vegetable Chop Suey",
        nickName: ["cs", "cm", "veg cs", "veg cm"],
        price: 9.95,
        category: ["Chow Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Vegetable Chow Mein",
        nickName: ["cs", "cm", "veg cs", "veg cm"],
        price: 10.95,
        category: ["Chow Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      //Honey Garlic
      {
        name: "Honey Garlic Spare Ribs",
        nickName: ["ho", "honey ribs"],
        price: 14.95,
        category: ["Honey & Curry"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Honey Garlic Chicken Wings",
        nickName: ["honey wings", "ho"],
        price: 12.95,
        category: ["Honey & Curry"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Honey Garlic Wontons",
        nickName: ["ho"],
        price: 7.95,
        category: ["Honey & Curry"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Honey Garlic Shrimps",
        nickName: ["ho"],
        price: 13.95,
        category: ["Honey & Curry"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      //Fried Rices
      {
        name: "Chicken Fried Rice",
        nickName: ["ch fr", "cfr", "fr"],
        price: 9.95,
        category: ["Fried Rice"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Fried Rice",
        nickName: ["bfr", "beef fr", "fr"],
        price: 9.95,
        category: ["Fried Rice"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Pork Fried Rice",
        nickName: ["fr", "pork fr"],
        price: 9.95,
        category: ["Fried Rice"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Shrimp Fried Rice",
        nickName: ["fr", "shrimp fr"],
        price: 12.95,
        category: ["Fried Rice"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Harmony Special Fried Rice",
        nickName: ["fr", "harm fr"],
        price: 12.95,
        category: ["Fried Rice"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Mushroom Fried Rice",
        nickName: ["fr", "mush fr", "mfr"],
        price: 9.95,
        category: ["Fried Rice"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Vegetable Fried Rice",
        nickName: ["fr", "veg fr", "plain fr"],
        price: 9.95,
        category: ["Fried Rice"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Steamed Rice (s)",
        nickName: ["fr"],
        price: 3.5,
        category: ["Fried Rice"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Steamed Rice (L)",
        nickName: ["fr"],
        price: 6.95,
        category: ["Fried Rice"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      //Vegetable Almonds

      {
        name: "Almond Guy Ding (Chicken)",
        nickName: ["vg", "di", "almd"],
        price: 12.95,
        category: ["Vegetable Almond"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Almond Beef Ding",
        nickName: ["vg", "di", "almd"],
        price: 12.95,
        category: ["Vegetable Almond"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Almond B.B.Q Pork Ding",
        nickName: ["vg", "di", "almd"],
        price: 12.95,
        category: ["Vegetable Almond"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Almond Shrimp Ding",
        nickName: ["vg", "di", "almd"],
        price: 14.95,
        category: ["Vegetable Almond"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Stir Fried Mixed Vegetables Almond",
        nickName: ["vg", "veg almd"],
        price: 12.95,
        category: ["Vegetable Almond"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      //Lo-Mein
      {
        name: "Chicken Lo-Mein",
        nickName: ["lm", "ch lm"],
        price: 12.95,
        category: ["Lo Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Lo-Mein",
        nickName: ["lm", "beef lm"],
        price: 13.95,
        category: ["Lo Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Pork Lo-Mein",
        nickName: ["lm", "p lm"],
        price: 13.95,
        category: ["Lo Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Shrimp Lo-Mein",
        nickName: ["lm", "shrimp lm"],
        price: 14.95,
        category: ["Lo Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Harmony Special Lo-Mein",
        nickName: ["lm", "harm lm"],
        price: 14.95,
        category: ["Lo Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Cantonese Style Chow Mein",
        nickName: ["lm", "cant cm"],
        price: 14.95,
        category: ["Lo Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Plain Lo-Mein",
        nickName: ["lm", "plain lm"],
        price: 12.95,
        category: ["Lo Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Mixed Vegetable Lo-Mein",
        nickName: ["lm", "veg lm"],
        price: 12.95,
        category: ["Lo Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken Shanghai",
        nickName: ["lm", "shanghai cm"],
        price: 13.95,
        category: ["Lo Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Shanghai",
        nickName: ["lm", "shanghai cm"],
        price: 13.95,
        category: ["Lo Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Singapore Chow Mein",
        nickName: ["lm"],
        price: 13.95,
        category: ["Lo Mein"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      //Egg Fu Young
      {
        name: "Chicken Egg Fu Young",
        nickName: ["fy", "ch efy", "efy"],
        price: 13.95,
        category: ["Egg Fu Young"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Egg Fu Young",
        nickName: ["fy", "beef efy", "efy"],
        price: 13.95,
        category: ["Egg Fu Young"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "B.B.Q Pork Egg Fu Young",
        nickName: ["fy", "bbq pork efy", "efy"],
        price: 13.95,
        category: ["Egg Fu Young"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Shrimp Egg Fu Young",
        nickName: ["fy", "shrimp efy", "efy"],
        price: 14.95,
        category: ["Egg Fu Young"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Mushroom Egg Fu Young",
        nickName: ["fy", "mush efy", "efy"],
        price: 13.95,
        category: ["Egg Fu Young"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },

      //Curry
      {
        name: "",
        nickName: [],
        price: 0.0,
        category: ["Honey & Curry"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Curry Chicken with Vegetables",
        nickName: ["cy", "curry ch"],
        price: 13.95,
        category: ["Honey & Curry"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Curry Beef with Vegetables",
        nickName: ["cy"],
        price: 13.95,
        category: ["Honey & Curry"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Curry Shrimp with Vegetables",
        nickName: ["cy"],
        price: 14.95,
        category: ["Honey & Curry"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Curry Chicken Wings with Vegetables",
        nickName: ["cy"],
        price: 14.95,
        category: ["Honey & Curry"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      //Szechaun
      {
        name: "Spicy Chicken",
        nickName: ["hot"],
        price: 13.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Spicy Beef",
        nickName: ["hot"],
        price: 13.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Kung Po Chicken",
        nickName: ["hot", "kp"],
        price: 13.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Kung Po Beef",
        nickName: ["hot", "kp"],
        price: 13.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Kung Pao Shrimps",
        nickName: ["hot", "kp"],
        price: 14.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Szechuan Chicken",
        nickName: ["hot", "sz ch"],
        price: 13.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Szechuan Beef",
        nickName: ["hot", "sz ch"],
        price: 13.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Satay Chicken",
        nickName: ["vg"],
        price: 13.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Satay Beef",
        nickName: ["vg"],
        price: 13.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Ginger Beef",
        nickName: ["hot"],
        price: 14.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Ma Po Tofu (Beef, Chicken Or Pork)",
        nickName: ["hot"],
        price: 13.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken Ma Po Tofu",
        nickName: ["hot"],
        price: 13.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Ma Po Tofu",
        nickName: ["hot"],
        price: 13.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Pork Ma Po Tofu",
        nickName: ["hot"],
        price: 13.95,
        category: ["Szechaun"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      //Seafood
      {
        name: "Seafood Platter",
        nickName: ["sf"],
        price: 16.95,
        category: ["Seafood"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Seafood Delight",
        nickName: ["sf"],
        price: 16.95,
        category: ["Seafood"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Soo Chow Scallops",
        nickName: ["sf"],
        price: 16.95,
        category: ["Seafood"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Soo Chow Har Kew",
        nickName: ["sf"],
        price: 14.95,
        category: ["Seafood"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Soo Chow Wonton",
        nickName: ["sf"],
        price: 13.95,
        category: ["Seafood"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Scallops and Mixed Vegetables",
        nickName: ["vg"],
        price: 16.95,
        category: ["Seafood"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Shrimp Lobster Sauce",
        nickName: ["sf"],
        price: 14.95,
        category: ["Seafood"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      //Popular Dishes
      {
        name: "Chicken Broccoli",
        nickName: ["vg"],
        price: 13.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Broccoli",
        nickName: ["vg"],
        price: 13.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Mixed Vegetables",
        nickName: ["vg"],
        price: 13.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Shrimp Mixed Vegetables",
        nickName: ["vg"],
        price: 15.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Moo Goo Guy Pan",
        nickName: ["vg", "mgp"],
        price: 13.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Mixed Oriental Vegetables",
        nickName: ["vg"],
        price: 12.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken Mushroom",
        nickName: ["vg"],
        price: 13.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Mushroom",
        nickName: ["vg"],
        price: 13.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken Snow Peas",
        nickName: ["vg"],
        price: 14.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Snow Peas",
        nickName: ["vg"],
        price: 14.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Shrimp Snow Peas",
        nickName: ["vg"],
        price: 15.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken with Green Pepper",
        nickName: ["vg"],
        price: 13.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef with Green Pepper",
        nickName: ["vg"],
        price: 13.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Shrimp with Green Pepper",
        nickName: ["vg"],
        price: 14.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Chinese Green",
        nickName: ["vg"],
        price: 13.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Pepper Steak",
        nickName: ["vg"],
        price: 13.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken Tomato",
        nickName: ["vg"],
        price: 13.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Tomato",
        nickName: ["vg"],
        price: 13.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken Baby Corn",
        nickName: ["vg"],
        price: 14.95,
        category: ["Popular Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      //Deep Fried Chicken eg. lemon chicken
      {
        name: "Lemon Chicken",
        nickName: ["og", "lem ch"],
        price: 11.95,
        category: ["Chickens"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "General Tao chicken",
        nickName: ["og", "gen toa", "gen ch", "gtch"],
        price: 11.95,
        category: ["Chickens"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Orange Chicken",
        nickName: ["og", "och"],
        price: 11.95,
        category: ["Chickens"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Sesame Chicken",
        nickName: ["og", "sem ch"],
        price: 11.95,
        category: ["Chickens"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Sweet & Sour Chicken",
        nickName: ["og", "sem ch"],
        price: 11.95,
        category: ["Chickens"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken Wings",
        nickName: ["ch wings"],
        price: 12.95,
        category: ["Chickens"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Almond Soo Guy",
        nickName: ["almd so guy"],
        price: 12.95,
        category: ["Chickens"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },

      //Chef Suggestions
      {
        name: "Tai Dop Voy",
        nickName: ["vg", "tdv"],
        price: 13.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken Mushroom & Broccoli",
        nickName: ["vg"],
        price: 14.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Mushroom & Broccoli",
        nickName: ["vg"],
        price: 14.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Soo Chow Wonton",
        nickName: ["vg"],
        price: 13.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Hong Sew Guy Kew",
        nickName: ["vg"],
        price: 13.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef and Onion",
        nickName: ["vg"],
        price: 14.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Wai Guy Kew",
        nickName: ["vg", "wgk"],
        price: 13.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chicken with Black Bean Sauce",
        nickName: ["vg"],
        price: 13.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef with Black Bean Sauce",
        nickName: ["vg"],
        price: 13.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Pepper Spare Ribs",
        nickName: ["vg"],
        price: 14.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Beef Mushroom with Oyster Sauce",
        nickName: ["vg"],
        price: 13.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Woo Dip Har",
        nickName: ["vg"],
        price: 15.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Golden Garlic Spare Ribs",
        nickName: ["hg"],
        price: 15.95,
        category: ["Chef Suggestions"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },

      //Canadian Dishes
      {
        name: "Spicy Potato Wedges",
        nickName: ["cd"],
        price: 7.95,
        category: ["Canadian Dishes"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Fish and Chips",
        nickName: ["cd"],
        price: 10.95,
        category: ["Canadian Dishes"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "French Fries",
        nickName: ["cd"],
        price: 4.95,
        category: ["Canadian Dishes"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Onion Rings",
        nickName: ["cd"],
        price: 4.95,
        category: ["Canadian Dishes"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },

      //Family Meals
      {
        name: "Dinner for 2",
        nickName: ["FD", "D/2"],
        price: 28.95,
        category: ["Family Dinners"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Dinner for 3",
        nickName: ["FD", "D/3"],
        price: 45.95,
        category: ["Family Dinners"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Dinner for 4",
        nickName: ["FD", "D/4"],
        price: 52.95,
        category: ["Family Dinners"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Dinner for 5",
        nickName: ["FD", "D/5"],
        price: 65.95,
        category: ["Family Dinners"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Dinner for 6",
        nickName: ["FD", "D/6"],
        price: 78.95,
        category: ["Family Dinners"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Dinner for 8",
        nickName: ["FD", "D/8"],
        price: 99.95,
        category: ["Family Dinners"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },

      //Extra
      {
        name: "Sweet & Sour Sauce (s)",
        nickName: ["sts (S)"],
        price: 1.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Sweet & Sour Sauce (L)",
        nickName: ["sts (L)"],
        price: 2.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Lemon Sauce (s)",
        nickName: ["sts (L)"],
        price: 1.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Lemon Sauce (L)",
        nickName: ["sts (L)"],
        price: 2.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Gravy (s)",
        nickName: ["sts (L)"],
        price: 1.5,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Honey Sauce",
        nickName: ["sts (L)"],
        price: 1.5,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Chop Sticks",
        nickName: [],
        price: 1.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Utensils",
        nickName: [],
        price: 1.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Extra Soy Sauce",
        nickName: [],
        price: 1.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Extra Plum Sauce",
        nickName: [],
        price: 1.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Extra Hot Sauce",
        nickName: [],
        price: 1.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Extra Mustard",
        nickName: [],
        price: 1.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Dry Noodles",
        nickName: [],
        price: 1.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Extra Fortune Cookies",
        nickName: [],
        price: 1.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Extra Spicy",
        nickName: [],
        price: 1.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Out of Town Delivery",
        nickName: [],
        price: 6.0,
        category: ["Extra Sauce"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      //Removal Items
      {
        name: "No onion",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No pepper",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No mushroom",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No garlic",
        nickName: [],
        price: 0.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No broccoli",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No celery",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No vegetable",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No chicken",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No beef",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No pork",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No shrimp",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "^ No Meat",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "All No Meat",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No egg",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No sauce",
        nickName: [],
        price: 0.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No carrot",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "No gravy",
        nickName: [],
        price: 0.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Sauce on side",
        nickName: [],
        price: 1.0,
        category: ["No Add"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },

      //Drinks
      {
        name: "Ice Tea Can",
        nickName: [],
        price: 1.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Ice Tea Bottle",
        nickName: [],
        price: 2.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Can Pepsi",
        nickName: [],
        price: 1.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Can Coke",
        nickName: [],
        price: 1.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Can Gingerale",
        nickName: [],
        price: 1.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Can Rootbeer",
        nickName: [],
        price: 1.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Can Sprite",
        nickName: [],
        price: 1.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Bottle Pepsi",
        nickName: [],
        price: 2.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Bottle Coke",
        nickName: [],
        price: 2.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Bottle Diet Coke",
        nickName: [],
        price: 2.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Bottle Diet Pepsi",
        nickName: [],
        price: 2.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Bottle Orange Crush",
        nickName: [],
        price: 2.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Bottle Gingerale",
        nickName: [],
        price: 2.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Bottle 7UP",
        nickName: [],
        price: 2.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
      {
        name: "Bottle Natural Water",
        nickName: [],
        price: 1.5,
        category: ["Drinks"],
        quantity: 1,
        modifiers: [],
        components: [],
        modifiable: false,
        swappable: true,
        selectionCategory: "",
      },
    ],
    menuCategories: ["Fried Rice", "Family Dinners", "Noodles", "Soup"],
  },
  reducers: {
    setMenuData: (state, { payload }) => {
      state.menuItems = payload;
    },
    setMenuCategories: (state, { payload }) => {
      state.menuCategories = payload;
    },
  },
});

export const { setMenuData, setMenuCategories } = menuDataSlice.actions;
export default menuDataSlice.reducer;
