export const ADDRESS_LIST = [
  "1st Alley",
  "1st Street",
  "2nd Street",
  "3rd Street",
  "4th Street",
  "5th Street",
  "Adams Avenue",
  "Alba Avenue",
  "Alexander Avenue",
  "Allen Street",
  "Andover Avenue",
  "Angus Street",
  "Ann Street",
  "Arbor Lane",
  "Argyle Street",
  "Armstrong Drive",
  "Balazs Court",
  "Baldwin Street",
  "Ball Alley",
  "Ball Street",
  "Barker Street",
  "Bear Street",
  "Beckett Boulevard",
  "Beech Boulevard",
  "Belfast Circle",
  "Bell Mill Sideroad",
  "Belmont Avenue",
  "Beth Court",
  "Bidwell Street",
  "Birch Drive",
  "Birdyway Drive",
  "Bloomer Street",
  "Bobolink Drive",
  "Bond Street",
  "Borden Crescent",
  "Brad Avenue",
  "Brasher Drive",
  "Bridge Street East",
  "Bridge Street West",
  "Bridle Path",
  "Broadway",
  "Brock Street East",
  "Brock Street West",
  "Brookside Lane",
  "Burdock Court",
  "Camdon Court",
  "Cardinal Court",
  "Carolina Street",
  "Cat Alley",
  "Catalpa Court",
  "Cedar Street",
  "Centennial Avenue",
  "Charles Street",
  "Charlotte Avenue",
  "Christie Street",
  "Christopher Court",
  "Clarence Street",
  "Clarke Street East",
  "Clarke Street West",
  "Clear Valley Drive",
  "Clearview Drive",
  "Colin Avenue",
  "Concession Street East",
  "Concession Street West",
  "Coon Alley",
  "Coreless Lane",
  "Coyle Lane",
  "Craig Street",
  "Cranberry Road",
  "Crocus Drive",
  "Daffodil Drive",
  "Daisy Court",
  "Delevan Crescent",
  "Demeyere Avenue",
  "Denis Court",
  "Denrich Avenue",
  "Denton Avenue",
  "Dereham Drive",
  "Devon Court",
  "Devonshire Avenue",
  "Dogwood Drive",
  "Duncan Street",
  "Durham Street",
  "Earle Street",
  "Ebert Alley",
  "Eden Place",
  "Edgewood Drive",
  "Edward Street",
  "Edwin Crescent",
  "Eleanor Court",
  "Elgin Street",
  "Elm Street",
  "Erie Court",
  "Esseltine Drive",
  "Fairfield Crescent",
  "Fairs Crescent",
  "Fairview Street",
  "Fairway Hills Boulevard",
  "Falcon Road",
  "Fernwood Drive",
  "Forest Glen Court",
  "Fox Alley",
  "Frances Street",
  "Frank Street",
  "George Street",
  "Gibson Drive",
  "Glendale Drive",
  "Glenridge Road",
  "Goldenrod Drive",
  "Goshen Street",
  "Gowrie Street East",
  "Gowrie Street West",
  "Greeneagle Drive",
  "Hale Street",
  "Hampton Court",
  "Hardy Avenue",
  "Harris Street",
  "Harvey Street",
  "Hawkins Crescent",
  "Hawthorne Street",
  "Hemlock Drive",
  "Herford Street",
  "Hickory Lane",
  "Highland Drive",
  "Highway 3",
  "Hilldrop Crescent",
  "Hilliker Alley",
  "Hillside Drive",
  "Hillyndale Road",
  "Hogarth Drive",
  "Holland Gate",
  "Hollier Drive",
  "Howe Avenue",
  "Hunter Crescent",
  "Hurley Avenue",
  "Hyman Street",
  "Jackson Court",
  "James Avenue",
  "Jane Street",
  "Jean Ferrie Court",
  "John Pound Road",
  "John Street",
  "Jones Crescent",
  "Joseph Street",
  "Judy Avenue",
  "Kamps Crescent",
  "Kara Lane",
  "King Street",
  "Lady Avenue",
  "Lamers Court",
  "Langrell Avenue",
  "Library Lane",
  "Lincoln Street",
  "Lindsay Street",
  "Lisgar Avenue",
  "Lisgar Court",
  "London Street East",
  "London Street West",
  "Lorraine Avenue",
  "Lowrie Crescent",
  "Lyndale Road",
  "Magnolia Court",
  "Magnolia Drive",
  "Maple Court",
  "Maple Lane",
  "Maple Villa Court",
  "Mary Street",
  "Mcdonald Court",
  "Mckenzie Street",
  "Miller Alley",
  "Moose Street",
  "Morning Glory Drive",
  "Myrtle Street",
  "Neff Alley",
  "Nelson Street",
  "Newell Road",
  "Niagara Street",
  "None",
  "North Street East",
  "North Street West",
  "Northern Lane",
  "Northview Drive",
  "Oak Street",
  "Old Vienna Road",
  "Ontario Street",
  "Otter Court",
  "Owl Drive",
  "Oxford Street",
  "Park Avenue",
  "Park Drive",
  "Park Place",
  "Parkdale Avenue",
  "Parkside Drive",
  "Parkwood Court",
  "Parkwood Drive",
  "Peach Street",
  "Pearl Street",
  "Pheasant Court",
  "Pine Avenue",
  "Pine Street",
  "Poplar Street",
  "Potters Road",
  "Potters Road North",
  "Primrose Drive",
  "Prospect Street",
  "Puc Alley",
  "Quarter Town Line",
  "Queen Street",
  "Railway Street",
  "Richards Court",
  "Ridge Boulevard",
  "Ridout Street East",
  "Ridout Street West",
  "Robin Road",
  "Rodgers Street",
  "Rokeby Orchard Road",
  "Rolph Street",
  "Rosalynn Circle",
  "Ross Street",
  "Rouse Street",
  "Sanders Crescent",
  "Sanders Street",
  "Sandy Court",
  "Segal Drive",
  "Seres Drive",
  "Simcoe Street",
  "Sinclair Drive",
  "South Ridge Road",
  "Spruce Street",
  "Stoney Court",
  "Stubbs Court",
  "Sycamore Drive",
  "Tanager Drive",
  "Taylor Lane",
  "Thistle Court",
  "Thomas Avenue",
  "Thorncliff Circle",
  "Tillson Avenue",
  "Tillson Street",
  "Town Line Road",
  "Trailview Drive",
  "Trillium Drive",
  "Trottier Drive",
  "Tulip Drive",
  "Valley Road",
  "Valley View Lane",
  "Van Norman Drive",
  "Van Street",
  "Vance Drive",
  "Venison Street East",
  "Venison Street West",
  "Verna Drive",
  "Victoria Street",
  "Victoria Way",
  "Vienna Road",
  "Virginia Street",
  "Wabash Road",
  "Walnut Drive",
  "Washington Grand Avenue",
  "Welding Street",
  "Wellington Street",
  "Weston Drive",
  "Westtown Line",
  "Whispering Pine Lane",
  "Wilkins Crescent",
  "William Street",
  "Wilson Avenue",
  "Windemere Avenue",
  "Winona Drive",
  "Wolf Street",
  "Wood Haven Drive",
  "Woodcock Drive",
  "Woodland Crescent",
  "Woodside Drive",
  "Wren Court",
  "Young Street",
];
export const MODIFIERS = [
  // No Add
  {
    name: "No Onions",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Peppers",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Garlic",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Broccoli",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Celery",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Vegetables",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Chicken",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Beef",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Shrimp",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Meat",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Egg",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Sauce",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Carrot",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Gravy",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Seafood",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Gluten",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "No Soy Sauce",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  {
    name: "Sauce on side",
    checked: false,
    modifyType: "No Add",
    price: 0.0,
  },
  // ----------------------------------------------------------- Extra ----------------------------------------------------------- //
  {
    name: "Add Onions",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Peppers",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Garlic",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Broccoli",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Celery",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Vegetables",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Chicken",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Beef",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Shrimp",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Meat",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Egg",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Sauce",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Carrot",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Gravy",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Seafood",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Gluten",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Add Soy Sauce",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
  {
    name: "Sauce on side",
    checked: false,
    modifyType: "Add",
    price: 1.0,
  },
];
